import { StyleSheet } from 'react-native';

export const CRISIS_COLORS = {
  BG: '#080E1A',
  CARD: '#0F1926',
  BORDER: '#182740',
  ACCENT: '#2EC4B6',
  TXT: '#E8EFF6',
  MUTED: '#4A6A8A',
  BREATHE_IN: '#2EC4B6',
  BREATHE_OUT: '#1A6B64',
} as const;

export const crisisStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CRISIS_COLORS.BG,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 8,
    gap: 12,
  },
  progressRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    height: 4,
  },
  progressSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: CRISIS_COLORS.BORDER,
  },
  progressSegmentDone: {
    backgroundColor: CRISIS_COLORS.ACCENT + '60',
  },
  progressSegmentActive: {
    backgroundColor: CRISIS_COLORS.ACCENT,
  },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: CRISIS_COLORS.CARD,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  landingCircle: {
    width: 140,
    height: 140,
    borderRadius: 70,
    backgroundColor: CRISIS_COLORS.ACCENT + '10',
    borderWidth: 2,
    borderColor: CRISIS_COLORS.ACCENT + '25',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 36,
  },
  landingTitle: {
    fontSize: 38,
    fontWeight: '300' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 16,
    letterSpacing: 1,
  },
  landingSubtitle: {
    fontSize: 18,
    color: CRISIS_COLORS.MUTED,
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 48,
  },
  bigButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 48,
    width: '100%',
    maxWidth: 340,
    minHeight: 64,
  },
  bigButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  bigButtonText: {
    fontSize: 19,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  quickCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 24,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '35',
    backgroundColor: CRISIS_COLORS.ACCENT + '08',
    minHeight: 56,
  },
  quickCallText: {
    fontSize: 17,
    fontWeight: '500' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  emergencyCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    minHeight: 52,
  },
  emergencyCallText: {
    fontSize: 16,
    color: '#EF5350',
    fontWeight: '500' as const,
  },
  stateActionsContainer: {
    marginTop: 32,
    width: '100%',
    maxWidth: 360,
  },
  stateLabel: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 12,
    textAlign: 'center',
  },
  stateLabelSecondary: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    marginTop: 24,
    marginBottom: 12,
    textAlign: 'left',
  },
  statePillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  statePill: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    backgroundColor: CRISIS_COLORS.CARD,
  },
  statePillActive: {
    borderColor: CRISIS_COLORS.ACCENT,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
  },
  statePillLabel: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '500' as const,
  },
  statePillLabelActive: {
    color: CRISIS_COLORS.TXT,
  },
  stateActionsList: {
    marginTop: 4,
    gap: 8,
  },
  stateActionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
  },
  stateActionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.ACCENT + '10',
    marginRight: 12,
  },
  stateActionTextWrap: {
    flex: 1,
  },
  stateActionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  stateActionSubtitle: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
  },
  stepLabel: {
    fontSize: 30,
    fontWeight: '300' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  stepHint: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 32,
    textAlign: 'center',
  },
  breathWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 240,
    marginBottom: 20,
  },
  breathCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.ACCENT + '06',
  },
  breathPhaseText: {
    fontSize: 22,
    fontWeight: '400' as const,
    letterSpacing: 1,
    marginBottom: 8,
  },
  breathTimerText: {
    fontSize: 52,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
  },
  breathCountText: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 24,
  },
  continueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginTop: 12,
    minHeight: 52,
  },
  continueBtnText: {
    fontSize: 16,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '500' as const,
  },
  groundingIconWrapper: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  groundingSense: {
    fontSize: 16,
    fontWeight: '700' as const,
    letterSpacing: 4,
    marginBottom: 12,
  },
  groundingPrompt: {
    fontSize: 20,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 28,
    fontWeight: '300' as const,
  },
  groundingChecks: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 24,
  },
  groundingCheckItem: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
  },
  groundingCheckNum: {
    fontSize: 20,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '300' as const,
  },
  groundingProgress: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
  },
  groundingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CRISIS_COLORS.BORDER,
  },
  urgeTimerCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.ACCENT + '35',
    backgroundColor: CRISIS_COLORS.ACCENT + '08',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  urgeTimerText: {
    fontSize: 48,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
    fontVariant: ['tabular-nums'],
  },
  urgeTimerLabel: {
    fontSize: 15,
    color: CRISIS_COLORS.ACCENT,
    marginTop: 8,
    fontWeight: '400' as const,
  },
  urgeProgressBar: {
    width: '100%',
    maxWidth: 300,
    height: 4,
    backgroundColor: CRISIS_COLORS.BORDER,
    borderRadius: 2,
    marginBottom: 8,
    overflow: 'hidden',
  },
  urgeProgressFill: {
    height: 4,
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 2,
  },
  urgeProgressLabel: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 28,
  },
  resetCard: {
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 28,
    padding: 40,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    width: '100%',
    maxWidth: 340,
  },
  resetPrompt: {
    fontSize: 24,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 36,
    fontWeight: '300' as const,
    letterSpacing: 0.3,
  },
  resetCounter: {
    fontSize: 14,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 24,
  },
  connectScroll: {
    flex: 1,
    width: '100%',
    maxWidth: 380,
  },
  connectScrollContent: {
    paddingBottom: 20,
  },
  connectSectionLabel: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: CRISIS_COLORS.MUTED,
    letterSpacing: 2,
    marginBottom: 12,
  },
  connectCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    minHeight: 80,
  },
  connectAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  connectAvatarText: {
    fontSize: 22,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  connectInfo: {
    flex: 1,
  },
  connectName: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  connectPhone: {
    fontSize: 14,
    color: CRISIS_COLORS.MUTED,
  },
  connectActions: {
    flexDirection: 'row',
    gap: 8,
  },
  connectCallBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectTextBtn: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: 26,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectTextBtnLabel: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  noContactsCard: {
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 28,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
  },
  noContactsText: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    textAlign: 'center',
    lineHeight: 24,
  },
  crisisLineCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    minHeight: 76,
  },
  crisisLineIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  crisisLineInfo: {
    flex: 1,
  },
  crisisLineName: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  crisisLineAvail: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
  },
  doneButton: {
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 24,
    paddingVertical: 20,
    alignItems: 'center',
    marginHorizontal: 28,
    marginTop: 8,
    minHeight: 64,
  },
  doneButtonText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  stepNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: CRISIS_COLORS.CARD,
    borderTopWidth: 1,
    borderTopColor: CRISIS_COLORS.BORDER,
  },
  stepNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  stepNavItemActive: {
    backgroundColor: CRISIS_COLORS.ACCENT + '12',
  },
  companionBar: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  companionBarInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '18',
    minHeight: 56,
  },
  companionBarDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CRISIS_COLORS.ACCENT,
  },
  companionBarText: {
    flex: 1,
    fontSize: 14,
    color: CRISIS_COLORS.TXT,
    lineHeight: 20,
    fontWeight: '400' as const,
  },
  relapsePlanBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 16,
    marginHorizontal: 20,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '18',
  },
  relapsePlanDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E53935',
  },
  relapsePlanTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
  },
  relapsePlanSubtitle: {
    fontSize: 12,
    color: CRISIS_COLORS.MUTED,
    marginTop: 2,
  },
});

