import { StyleSheet } from 'react-native';

export const CRISIS_COLORS = {
  BG: '#080E1A',
  CARD: '#0F1926',
  BORDER: '#182740',
  ACCENT: '#2EC4B6',
  TXT: '#E8EFF6',
  MUTED: '#4A6A8A',
  BREATHE_IN: '#2EC4B6',
  BREATHE_OUT: '#1A6B64',
} as const;

export const crisisStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: CRISIS_COLORS.BG,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 8,
    gap: 12,
  },
  progressRow: {
    flex: 1,
    flexDirection: 'row',
    gap: 4,
    height: 4,
  },
  progressSegment: {
    flex: 1,
    height: 4,
    borderRadius: 2,
    backgroundColor: CRISIS_COLORS.BORDER,
  },
  progressSegmentDone: {
    backgroundColor: CRISIS_COLORS.ACCENT + '60',
  },
  progressSegmentActive: {
    backgroundColor: CRISIS_COLORS.ACCENT,
  },
  closeBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: CRISIS_COLORS.CARD,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stepContainer: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    // Reserve space for the companion + relapse CTA so step content
    // doesn't paint underneath them on shorter screens.
    paddingBottom: 120,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
  },
  /**
   * Grounding / Urge / Reset: column between header and companion — no overflow under companion.
   * Header + footer shrink-wrap; main flexes and centers its content.
   */
  crisisStepFitOuter: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 4,
  },
  crisisStepFitHeader: {
    flexShrink: 0,
    alignItems: 'center',
    width: '100%',
  },
  /** Tighter than stepHint so title block stays compact */
  crisisStepFitHint: {
    marginBottom: 8,
  },
  crisisStepFitMain: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  /** ScrollView content inside crisisStepFitMain: fills height when short, scrolls only if needed */
  crisisStepFitMainScrollContent: {
    flexGrow: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 4,
  },
  crisisStepFitFooter: {
    flexShrink: 0,
    alignItems: 'center',
    width: '100%',
  },
  /** Single full-height scroll column (Ride the Wave, Reset when all content scrolls together) */
  crisisStepSingleScrollOuter: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    alignSelf: 'stretch',
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 4,
  },
  /** Title + body + actions in one scroll (Ride the Wave, Reset) */
  crisisStepFullScrollContent: {
    flexGrow: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingVertical: 4,
    paddingBottom: 12,
  },
  /** Reach Out: maximize scroll area; done CTA sits flush above companion */
  connectStepOuter: {
    flex: 1,
    minHeight: 0,
    width: '100%',
    alignSelf: 'stretch',
    flexDirection: 'column',
    paddingHorizontal: 28,
    paddingTop: 6,
    paddingBottom: 0,
  },
  doneButtonConnect: {
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 24,
    paddingVertical: 16,
    alignItems: 'center',
    alignSelf: 'stretch',
    marginTop: 8,
    marginBottom: 0,
    minHeight: 56,
  },
  /** Breathe step: scrolls within the area above the companion bar so the Continue CTA is never covered. */
  breathingStepContainer: {
    flexGrow: 1,
    flexShrink: 1,
    minHeight: 0,
    paddingTop: 20,
    paddingHorizontal: 28,
  },
  breathingStepScrollContent: {
    flexGrow: 1,
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingBottom: 20,
  },
  landingStepContainer: {
    alignItems: 'center',
    // Important: Crisis Landing is rendered alongside `CrisisStateActions`.
    // Using a non-flex container and no translate-based slide animation
    // prevents overlap with the action cards.
    justifyContent: 'flex-start',
    paddingHorizontal: 28,
  },
  landingCircle: {
    width: 112,
    height: 112,
    borderRadius: 56,
    backgroundColor: CRISIS_COLORS.ACCENT + '10',
    borderWidth: 2,
    borderColor: CRISIS_COLORS.ACCENT + '25',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  landingTitle: {
    fontSize: 38,
    fontWeight: '300' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 16,
    letterSpacing: 1,
  },
  landingSubtitle: {
    fontSize: 18,
    color: CRISIS_COLORS.MUTED,
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 20,
  },
  bigButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 48,
    width: '100%',
    maxWidth: 340,
    minHeight: 64,
  },
  bigButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.97 }],
  },
  bigButtonText: {
    fontSize: 19,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  quickCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 24,
    paddingVertical: 16,
    paddingHorizontal: 32,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '35',
    backgroundColor: CRISIS_COLORS.ACCENT + '08',
    minHeight: 56,
  },
  quickCallText: {
    fontSize: 17,
    fontWeight: '500' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  emergencyCallBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 24,
    minHeight: 52,
  },
  emergencyCallText: {
    fontSize: 16,
    color: '#EF5350',
    fontWeight: '500' as const,
  },
  stateActionsContainer: {
    marginTop: 12,
    width: '100%',
    maxWidth: 360,
  },
  stateLabel: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 12,
    textAlign: 'center',
  },
  stateLabelSecondary: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    marginTop: 24,
    marginBottom: 12,
    textAlign: 'left',
  },
  statePillsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'center',
  },
  statePill: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    backgroundColor: CRISIS_COLORS.CARD,
  },
  statePillActive: {
    borderColor: CRISIS_COLORS.ACCENT,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
  },
  statePillLabel: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '500' as const,
  },
  statePillLabelActive: {
    color: CRISIS_COLORS.TXT,
  },
  stateActionsList: {
    marginTop: 4,
    gap: 8,
  },
  stateActionCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
  },
  stateActionIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.ACCENT + '10',
    marginRight: 12,
  },
  stateActionTextWrap: {
    flex: 1,
  },
  stateActionTitle: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  stateActionSubtitle: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
  },
  stepLabel: {
    fontSize: 30,
    fontWeight: '300' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 8,
    letterSpacing: 0.5,
  },
  stepHint: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 32,
    textAlign: 'center',
  },
  breathWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 240,
    marginBottom: 20,
  },
  breathCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.ACCENT + '06',
  },
  breathPhaseText: {
    fontSize: 22,
    fontWeight: '400' as const,
    letterSpacing: 1,
    marginBottom: 8,
  },
  breathTimerText: {
    fontSize: 52,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
  },
  breathCountText: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 24,
  },
  /** Cycle line + inline Continue (crisis Breathe) — same typography. */
  breathMetaText: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '500' as const,
  },
  breathContinueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    alignSelf: 'center',
    marginTop: 2,
  },
  /** Compact circle so cycle + Continue fit on screen without scrolling on typical phones. */
  crisisBreathWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    height: 188,
    marginBottom: 12,
  },
  crisisBreathCircle: {
    width: 176,
    height: 176,
    borderRadius: 88,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.ACCENT + '06',
  },
  crisisBreathPhaseText: {
    fontSize: 19,
    fontWeight: '400' as const,
    letterSpacing: 1,
    marginBottom: 6,
  },
  crisisBreathTimerText: {
    fontSize: 40,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
  },
  continueBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 16,
    paddingHorizontal: 24,
    marginTop: 12,
    minHeight: 52,
  },
  continueBtnText: {
    fontSize: 16,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '500' as const,
  },
  continueBtnComplete: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 16,
    paddingHorizontal: 28,
    marginTop: 12,
    minHeight: 52,
    alignSelf: 'stretch',
    borderRadius: 999,
    backgroundColor: CRISIS_COLORS.ACCENT,
    shadowColor: CRISIS_COLORS.ACCENT,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 6,
  },
  continueBtnCompleteText: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600' as const,
  },
  groundingIconWrapper: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
  },
  groundingSense: {
    fontSize: 16,
    fontWeight: '700' as const,
    letterSpacing: 4,
    marginBottom: 12,
  },
  groundingPrompt: {
    fontSize: 20,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 28,
    marginBottom: 28,
    fontWeight: '300' as const,
  },
  groundingChecks: {
    flexDirection: 'row',
    gap: 14,
    marginBottom: 24,
  },
  groundingCheckItem: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
  },
  groundingCheckNum: {
    fontSize: 20,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '300' as const,
  },
  groundingProgress: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 8,
  },
  groundingDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CRISIS_COLORS.BORDER,
  },
  /** Crisis Ground Yourself — fits in step column */
  crisisGroundingIconWrap: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  crisisGroundingSense: {
    fontSize: 15,
    fontWeight: '700' as const,
    letterSpacing: 3,
    marginBottom: 6,
  },
  crisisGroundingPrompt: {
    fontSize: 17,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 12,
    fontWeight: '300' as const,
  },
  crisisGroundingChecks: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 10,
  },
  crisisGroundingCheckItem: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.BORDER,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
  },
  crisisGroundingCheckNum: {
    fontSize: 17,
    color: CRISIS_COLORS.MUTED,
    fontWeight: '300' as const,
  },
  crisisGroundingProgress: {
    flexDirection: 'row',
    gap: 5,
    marginBottom: 4,
  },
  urgeTimerCircle: {
    width: 220,
    height: 220,
    borderRadius: 110,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.ACCENT + '35',
    backgroundColor: CRISIS_COLORS.ACCENT + '08',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  urgeTimerText: {
    fontSize: 48,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
    fontVariant: ['tabular-nums'],
  },
  urgeTimerLabel: {
    fontSize: 15,
    color: CRISIS_COLORS.ACCENT,
    marginTop: 8,
    fontWeight: '400' as const,
  },
  urgeProgressBar: {
    width: '100%',
    maxWidth: 300,
    height: 4,
    backgroundColor: CRISIS_COLORS.BORDER,
    borderRadius: 2,
    marginBottom: 8,
    overflow: 'hidden',
  },
  urgeProgressFill: {
    height: 4,
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 2,
  },
  urgeProgressLabel: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 28,
  },
  crisisUrgeTimerCircleCompact: {
    width: 136,
    height: 136,
    borderRadius: 68,
    borderWidth: 2,
    borderColor: CRISIS_COLORS.ACCENT + '35',
    backgroundColor: CRISIS_COLORS.ACCENT + '08',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  crisisUrgeTimerTextCompact: {
    fontSize: 28,
    fontWeight: '200' as const,
    color: CRISIS_COLORS.TXT,
    fontVariant: ['tabular-nums'],
  },
  crisisUrgeTimerLabelCompact: {
    fontSize: 12,
    color: CRISIS_COLORS.ACCENT,
    marginTop: 4,
    fontWeight: '400' as const,
  },
  crisisUrgeProgressBarCompact: {
    width: '100%',
    maxWidth: 300,
    height: 4,
    backgroundColor: CRISIS_COLORS.BORDER,
    borderRadius: 2,
    marginBottom: 4,
    overflow: 'hidden',
  },
  crisisUrgeProgressLabelCompact: {
    fontSize: 12,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 8,
    textAlign: 'center',
  },
  crisisBigButtonCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 20,
    paddingVertical: 12,
    paddingHorizontal: 32,
    width: '100%',
    maxWidth: 340,
    minHeight: 48,
  },
  resetCard: {
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 28,
    padding: 40,
    alignItems: 'center',
    marginBottom: 24,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    width: '100%',
    maxWidth: 340,
  },
  resetPrompt: {
    fontSize: 24,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 36,
    fontWeight: '300' as const,
    letterSpacing: 0.3,
  },
  resetCounter: {
    fontSize: 14,
    color: CRISIS_COLORS.MUTED,
    marginBottom: 24,
  },
  crisisResetCardCompact: {
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 22,
    paddingVertical: 14,
    paddingHorizontal: 18,
    alignItems: 'center',
    marginBottom: 0,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    width: '100%',
    maxWidth: 340,
  },
  crisisResetPromptCompact: {
    fontSize: 18,
    color: CRISIS_COLORS.TXT,
    textAlign: 'center',
    lineHeight: 26,
    fontWeight: '300' as const,
    letterSpacing: 0.3,
  },
  crisisResetCounterCompact: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
    marginTop: 4,
    marginBottom: 6,
  },
  connectScroll: {
    flex: 1,
    width: '100%',
    maxWidth: 380,
  },
  connectScrollContent: {
    paddingBottom: 8,
  },
  connectSectionLabel: {
    fontSize: 11,
    fontWeight: '700' as const,
    color: CRISIS_COLORS.MUTED,
    letterSpacing: 2,
    marginBottom: 12,
  },
  connectCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    minHeight: 80,
  },
  connectAvatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  connectAvatarText: {
    fontSize: 22,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  connectInfo: {
    flex: 1,
  },
  connectName: {
    fontSize: 17,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  connectPhone: {
    fontSize: 14,
    color: CRISIS_COLORS.MUTED,
  },
  connectActions: {
    flexDirection: 'row',
    gap: 8,
  },
  connectCallBtn: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#4CAF50',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectTextBtn: {
    height: 52,
    paddingHorizontal: 20,
    borderRadius: 26,
    backgroundColor: CRISIS_COLORS.ACCENT + '20',
    alignItems: 'center',
    justifyContent: 'center',
  },
  connectTextBtnLabel: {
    fontSize: 15,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.ACCENT,
  },
  noContactsCard: {
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 28,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
  },
  noContactsText: {
    fontSize: 15,
    color: CRISIS_COLORS.MUTED,
    textAlign: 'center',
    lineHeight: 24,
  },
  crisisLineCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 18,
    padding: 18,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.BORDER,
    minHeight: 76,
  },
  crisisLineIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  crisisLineInfo: {
    flex: 1,
  },
  crisisLineName: {
    fontSize: 16,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
    marginBottom: 2,
  },
  crisisLineAvail: {
    fontSize: 13,
    color: CRISIS_COLORS.MUTED,
  },
  doneButton: {
    backgroundColor: CRISIS_COLORS.ACCENT,
    borderRadius: 24,
    paddingVertical: 20,
    alignItems: 'center',
    marginHorizontal: 28,
    marginTop: 8,
    minHeight: 64,
  },
  doneButtonText: {
    fontSize: 18,
    fontWeight: '600' as const,
    color: '#FFFFFF',
  },
  stepNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: CRISIS_COLORS.CARD,
    borderTopWidth: 1,
    borderTopColor: CRISIS_COLORS.BORDER,
  },
  stepNavItem: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 52,
    height: 52,
    borderRadius: 26,
  },
  stepNavItemActive: {
    backgroundColor: CRISIS_COLORS.ACCENT + '12',
  },
  companionBar: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  companionBarInner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '18',
    minHeight: 56,
  },
  companionBarDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: CRISIS_COLORS.ACCENT,
  },
  companionBarText: {
    flex: 1,
    fontSize: 14,
    color: CRISIS_COLORS.TXT,
    lineHeight: 20,
    fontWeight: '400' as const,
  },
  relapsePlanBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: CRISIS_COLORS.CARD,
    borderRadius: 16,
    marginHorizontal: 20,
    marginBottom: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    borderWidth: 1,
    borderColor: CRISIS_COLORS.ACCENT + '18',
  },
  relapsePlanDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#E53935',
  },
  relapsePlanTitle: {
    fontSize: 14,
    fontWeight: '600' as const,
    color: CRISIS_COLORS.TXT,
  },
  relapsePlanSubtitle: {
    fontSize: 12,
    color: CRISIS_COLORS.MUTED,
    marginTop: 2,
  },
});

