import { WorkbookSection } from '../../types';

export const WORKBOOK_SECTIONS_16_20: WorkbookSection[] = [
  {
    id: 'sec-16',
    title: 'Purpose & Meaning',
    description: 'Discover what gives your life meaning',
    unlockMilestoneDays: 90,
    questions: [
      { id: 's16q1', type: 'reflection', question: 'What gives your life meaning right now?' },
      { id: 's16q2', type: 'journaling', question: 'If you could do anything in the world and money was not an issue, what would you do?' },
      { id: 's16q3', type: 'reflection', question: 'What activities make you lose track of time? What is it about them?' },
      { id: 's16q4', type: 'assignment', question: 'Write your personal values - the top 10 things that matter most to you. Rank them.' },
      { id: 's16q5', type: 'reflection', question: 'How does your recovery connect to a larger purpose?' },
      { id: 's16q6', type: 'journaling', question: 'Write about a cause or issue you care deeply about. Why does it matter to you?' },
      { id: 's16q7', type: 'exercise', question: 'Volunteer for a cause this week or help someone in need. Write about the experience.' },
      { id: 's16q8', type: 'reflection', question: 'What legacy do you want to leave behind?' },
      { id: 's16q9', type: 'assignment', question: 'Set 3 meaningful goals for the next 6 months that align with your values.' },
      { id: 's16q10', type: 'reflection', question: 'How can you use your experience with addiction to help others?' },
      { id: 's16q11', type: 'journaling', question: 'Write about a time when you felt truly purposeful. What were you doing?' },
      { id: 's16q12', type: 'reflection', question: 'What role does spirituality or faith play in your sense of purpose?' },
      { id: 's16q13', type: 'assignment', question: 'Create a "purpose statement" for your life in recovery. Make it specific and inspiring.' },
      { id: 's16q14', type: 'reflection', question: 'How does serving others contribute to your recovery and sense of meaning?' },
      { id: 's16q15', type: 'exercise', question: 'Spend 30 minutes doing something solely for someone else. Write about how it made you feel.' },
      { id: 's16q16', type: 'journaling', question: 'What would your ideal contribution to the world look like?' },
      { id: 's16q17', type: 'reflection', question: 'How has your sense of purpose changed since beginning recovery?' },
      { id: 's16q18', type: 'assignment', question: 'Research local organizations where you could volunteer or contribute. Write about options that interest you.' },
      { id: 's16q19', type: 'reflection', question: 'What skills or talents do you have that could benefit others?' },
      { id: 's16q20', type: 'journaling', question: 'Write your "purpose autobiography" - how your life experiences have prepared you for your purpose.' },
    ],
  },
  {
    id: 'sec-17',
    title: 'Forgiveness',
    description: 'Release the burden of resentment and self-blame',
    unlockMilestoneDays: 90,
    questions: [
      { id: 's17q1', type: 'reflection', question: 'Who do you need to forgive? Make a complete list.' },
      { id: 's17q2', type: 'journaling', question: 'Write about why forgiving yourself is the hardest part. What do you need to forgive yourself for?' },
      { id: 's17q3', type: 'reflection', question: 'What does forgiveness mean to you? What does it not mean?' },
      { id: 's17q4', type: 'assignment', question: 'Choose one person from your list and write about what forgiving them would look like practically.' },
      { id: 's17q5', type: 'reflection', question: 'How does holding onto unforgiveness affect your physical health and recovery?' },
      { id: 's17q6', type: 'exercise', question: 'Write a forgiveness letter to yourself for everything your addiction caused. Read it out loud.' },
      { id: 's17q7', type: 'journaling', question: 'Describe a time when someone forgave you. How did it feel?' },
      { id: 's17q8', type: 'reflection', question: 'What is the difference between forgiving and condoning what happened?' },
      { id: 's17q9', type: 'assignment', question: 'Make a list of amends you need to make. Prioritize them by urgency and readiness.' },
      { id: 's17q10', type: 'reflection', question: 'Are there people in your life who need to forgive you? How can you make that possible?' },
      { id: 's17q11', type: 'exercise', question: 'Practice a forgiveness meditation: Visualize releasing anger toward one person. Write about the experience.' },
      { id: 's17q12', type: 'journaling', question: 'Write about what your life would feel like if you were completely at peace with your past.' },
      { id: 's17q13', type: 'reflection', question: 'How can you make amends without expecting forgiveness in return?' },
      { id: 's17q14', type: 'assignment', question: 'Take one small step toward making amends with someone this week. Write about the process.' },
      { id: 's17q15', type: 'reflection', question: 'What role does pride play in your resistance to forgiveness?' },
      { id: 's17q16', type: 'journaling', question: 'Write about the weight you carry from unforgiveness. What would it feel like to set it down?' },
      { id: 's17q17', type: 'reflection', question: 'How does self-forgiveness differ from making excuses?' },
      { id: 's17q18', type: 'exercise', question: 'Write "I forgive myself for..." and complete the sentence 10 different ways. Sit with each one.' },
      { id: 's17q19', type: 'reflection', question: 'What have you learned about forgiveness through your recovery journey?' },
      { id: 's17q20', type: 'journaling', question: 'Write about a future where forgiveness has set you completely free. What does that life look like?' },
    ],
  },
  {
    id: 'sec-18',
    title: 'Relapse Prevention',
    description: 'Build a strong defense against relapse',
    unlockMilestoneDays: 90,
    questions: [
      { id: 's18q1', type: 'reflection', question: 'What are your biggest risk factors for relapse right now?' },
      { id: 's18q2', type: 'assignment', question: 'Create a detailed relapse prevention plan with at least 10 strategies.' },
      { id: 's18q3', type: 'journaling', question: 'Write about a past relapse (or near-relapse). What led up to it? What warning signs did you miss?' },
      { id: 's18q4', type: 'reflection', question: 'What are the early warning signs that you might be heading toward relapse?' },
      { id: 's18q5', type: 'assignment', question: 'List your top 10 relapse triggers and a specific coping strategy for each one.' },
      { id: 's18q6', type: 'reflection', question: 'How does the "just this once" mentality affect your recovery?' },
      { id: 's18q7', type: 'exercise', question: 'Role-play a high-risk situation in your mind. Visualize yourself successfully navigating it. Write the scene.' },
      { id: 's18q8', type: 'reflection', question: 'Who can you call at any hour if you feel close to relapsing? List at least 3 people.' },
      { id: 's18q9', type: 'assignment', question: 'Create a "relapse emergency card" with phone numbers, affirmations, and immediate actions to take.' },
      { id: 's18q10', type: 'journaling', question: 'Write about what would happen in the first 24 hours after a relapse. Be specific and honest.' },
      { id: 's18q11', type: 'reflection', question: 'How do you handle boredom in recovery? Does boredom tend to make staying on track harder for you?' },
      { id: 's18q12', type: 'assignment', question: 'Plan your response to 5 high-risk scenarios (party, argument, bad news, loneliness, celebration).' },
      { id: 's18q13', type: 'reflection', question: 'What does emotional relapse look like for you? How about mental relapse?' },
      { id: 's18q14', type: 'exercise', question: 'Practice "urge surfing": When a craving arises, observe it without acting. Time it. Write about the experience.' },
      { id: 's18q15', type: 'reflection', question: 'How does complacency in recovery lead to relapse?' },
      { id: 's18q16', type: 'journaling', question: 'Write a letter to yourself to read if you ever feel close to relapsing. Make it powerful.' },
      { id: 's18q17', type: 'reflection', question: 'What social situations feel hardest for you? How will you handle them?' },
      { id: 's18q18', type: 'assignment', question: 'Create a daily check-in practice to monitor your recovery health. What questions will you ask yourself?' },
      { id: 's18q19', type: 'reflection', question: 'If relapse happens, how will you get back on track? Having a plan reduces shame.' },
      { id: 's18q20', type: 'journaling', question: 'Write about why you believe you can stay sober long-term. What gives you that confidence?' },
    ],
  },
  {
    id: 'sec-19',
    title: 'Spirituality & Inner Peace',
    description: 'Explore your spiritual dimension of recovery',
    unlockMilestoneDays: 180,
    questions: [
      { id: 's19q1', type: 'reflection', question: 'What does spirituality mean to you? (It does not have to involve religion.)' },
      { id: 's19q2', type: 'journaling', question: 'Describe a moment when you felt deeply connected to something greater than yourself.' },
      { id: 's19q3', type: 'reflection', question: 'How can a spiritual practice support your recovery?' },
      { id: 's19q4', type: 'exercise', question: 'Spend 15 minutes in quiet contemplation or prayer. Write about what arose.' },
      { id: 's19q5', type: 'reflection', question: 'What does inner peace mean to you? Have you experienced it?' },
      { id: 's19q6', type: 'assignment', question: 'Explore a spiritual practice new to you (meditation, prayer, nature walk, gratitude ritual). Write about the experience.' },
      { id: 's19q7', type: 'journaling', question: 'Write about your relationship with the concept of a Higher Power or the universe.' },
      { id: 's19q8', type: 'reflection', question: 'How does surrender differ from giving up?' },
      { id: 's19q9', type: 'exercise', question: 'Practice gratitude: Write 20 things you are grateful for right now, no matter how small.' },
      { id: 's19q10', type: 'reflection', question: 'What role does hope play in your spiritual life and recovery?' },
      { id: 's19q11', type: 'journaling', question: 'Write about a time when something unexpectedly good happened in your recovery. Was it coincidence or something more?' },
      { id: 's19q12', type: 'reflection', question: 'How do you find meaning in suffering?' },
      { id: 's19q13', type: 'assignment', question: 'Create a daily spiritual practice routine (even 5 minutes). Follow it for a week and report.' },
      { id: 's19q14', type: 'reflection', question: 'What does faith mean to you in the context of recovery?' },
      { id: 's19q15', type: 'exercise', question: 'Spend time in nature without distraction. Observe the beauty around you. Write about what you notice.' },
      { id: 's19q16', type: 'journaling', question: 'Write about forgiveness from a spiritual perspective. How does it connect to peace?' },
      { id: 's19q17', type: 'reflection', question: 'How can you cultivate more peace in your daily life?' },
      { id: 's19q18', type: 'assignment', question: 'Read or listen to something spiritually inspiring this week. Write about what resonated with you.' },
      { id: 's19q19', type: 'reflection', question: 'What spiritual truths have you discovered through your recovery journey?' },
      { id: 's19q20', type: 'journaling', question: 'Write about what serenity looks like in your life. How close are you to it?' },
    ],
  },
  {
    id: 'sec-20',
    title: 'Career & Ambition',
    description: 'Rebuild your professional life and goals',
    unlockMilestoneDays: 180,
    questions: [
      { id: 's20q1', type: 'reflection', question: 'How has addiction affected your career or professional life?' },
      { id: 's20q2', type: 'journaling', question: 'Describe your dream career or professional achievement. Why does it matter to you?' },
      { id: 's20q3', type: 'assignment', question: 'Set 3 professional goals for the next year. Break each into actionable steps.' },
      { id: 's20q4', type: 'reflection', question: 'What skills or talents do you have that are underutilized?' },
      { id: 's20q5', type: 'exercise', question: 'Update or create your resume or portfolio this week. Write about how it feels to see your accomplishments.' },
      { id: 's20q6', type: 'reflection', question: 'How does recovery give you a competitive advantage in your professional life?' },
      { id: 's20q7', type: 'journaling', question: 'Write about workplace triggers and how you plan to handle them.' },
      { id: 's20q8', type: 'assignment', question: 'Identify 3 professional development opportunities (courses, certifications, mentoring) you can pursue.' },
      { id: 's20q9', type: 'reflection', question: 'What is holding you back professionally? How much of it is related to your addiction history?' },
      { id: 's20q10', type: 'journaling', question: 'Write about the intersection of purpose and career. How can your work become more meaningful?' },
      { id: 's20q11', type: 'reflection', question: 'How do you handle professional stress without reverting to old habits?' },
      { id: 's20q12', type: 'assignment', question: 'Create a 5-year professional plan. Where do you want to be? How will you get there?' },
      { id: 's20q13', type: 'reflection', question: 'What professional relationships do you need to rebuild or develop?' },
      { id: 's20q14', type: 'exercise', question: 'Reach out to one professional contact or mentor this week. Write about the interaction.' },
      { id: 's20q15', type: 'reflection', question: 'How can you be honest about your recovery in professional settings without oversharing?' },
      { id: 's20q16', type: 'journaling', question: 'Write about a professional setback caused by addiction. What did you learn from it?' },
      { id: 's20q17', type: 'reflection', question: 'What does work-life balance look like in your recovery?' },
      { id: 's20q18', type: 'assignment', question: 'Learn one new skill this month that could benefit your career. Track your progress.' },
      { id: 's20q19', type: 'reflection', question: 'How does financial recovery connect to professional growth?' },
      { id: 's20q20', type: 'journaling', question: 'Imagine writing your professional biography 10 years from now. What does it say?' },
    ],
  },
];
