import { WorkbookSection } from '../../types';

export const WORKBOOK_SECTIONS_21_25: WorkbookSection[] = [
  {
    id: 'sec-21',
    title: 'Creativity & Joy',
    description: 'Reconnect with play, creativity, and fun',
    unlockMilestoneDays: 180,
    questions: [
      { id: 's21q1', type: 'reflection', question: 'When was the last time you did something creative? What was it?' },
      { id: 's21q2', type: 'exercise', question: 'Create something today - draw, write a poem, cook something new, build something. Write about the experience.' },
      { id: 's21q3', type: 'journaling', question: 'Write about a hobby or interest you abandoned during addiction. Would you like to return to it?' },
      { id: 's21q4', type: 'reflection', question: 'How does creativity support your recovery?' },
      { id: 's21q5', type: 'assignment', question: 'List 15 activities that bring you genuine joy. How many have you done in the past month?' },
      { id: 's21q6', type: 'reflection', question: 'What did you love doing as a child? How can you incorporate that into your life now?' },
      { id: 's21q7', type: 'exercise', question: 'Spend 30 minutes doing something playful with no purpose other than fun. Write about it.' },
      { id: 's21q8', type: 'journaling', question: 'Write about laughter. When did you last laugh until you cried? Describe the moment.' },
      { id: 's21q9', type: 'reflection', question: 'How does addiction steal joy? How does recovery restore it?' },
      { id: 's21q10', type: 'assignment', question: 'Plan a "joy date" for yourself this week - an activity purely for pleasure. Execute it and write about it.' },
      { id: 's21q11', type: 'reflection', question: 'What music moves you? How does it affect your mood and recovery?' },
      { id: 's21q12', type: 'exercise', question: 'Write a short story, poem, or song about your recovery journey. Share it if you feel comfortable.' },
      { id: 's21q13', type: 'reflection', question: 'How can you bring more spontaneity into your structured recovery life?' },
      { id: 's21q14', type: 'journaling', question: 'Describe your perfect day of joy and creativity. What would you do from morning to night?' },
      { id: 's21q15', type: 'reflection', question: 'What fears hold you back from being creative or playful?' },
      { id: 's21q16', type: 'assignment', question: 'Try a creative activity you have never done before this week (painting, pottery, writing, dance, etc.). Report on it.' },
      { id: 's21q17', type: 'reflection', question: 'How does beauty in art, nature, or music affect your emotional state?' },
      { id: 's21q18', type: 'exercise', question: 'Create a playlist of songs that represent different stages of your recovery. Write about your choices.' },
      { id: 's21q19', type: 'reflection', question: 'How can you make your recovery journey itself a creative expression?' },
      { id: 's21q20', type: 'journaling', question: 'Write a love letter to life. Tell it everything you appreciate about being alive and sober.' },
    ],
  },
  {
    id: 'sec-22',
    title: 'Giving Back',
    description: 'Use your experience to help others',
    unlockMilestoneDays: 365,
    questions: [
      { id: 's22q1', type: 'reflection', question: 'How can your recovery story help someone else?' },
      { id: 's22q2', type: 'journaling', question: 'Write about a time when someone in recovery helped you. How did it impact you?' },
      { id: 's22q3', type: 'assignment', question: 'Identify 3 ways you can give back to people walking similar paths this month.' },
      { id: 's22q4', type: 'reflection', question: 'What does being a mentor or sponsor mean to you? Are you ready for that role?' },
      { id: 's22q5', type: 'exercise', question: 'Perform 3 acts of kindness this week. Write about each one and how it made you feel.' },
      { id: 's22q6', type: 'reflection', question: 'How does helping others strengthen your own recovery?' },
      { id: 's22q7', type: 'journaling', question: 'Write the advice you wish someone had given you at the start of your recovery.' },
      { id: 's22q8', type: 'assignment', question: 'Research support groups or organizations where you could volunteer. Create a plan to get involved.' },
      { id: 's22q9', type: 'reflection', question: 'What unique perspective does your experience give you that could benefit others?' },
      { id: 's22q10', type: 'exercise', question: 'Share your story (or part of it) with someone who might benefit. Write about the experience.' },
      { id: 's22q11', type: 'reflection', question: 'How can you give back without depleting your own recovery reserves?' },
      { id: 's22q12', type: 'journaling', question: 'Write about the ripple effect of recovery - how your sobriety impacts everyone around you.' },
      { id: 's22q13', type: 'assignment', question: 'Create a "giving back" plan for the next year. Include regular and one-time activities.' },
      { id: 's22q14', type: 'reflection', question: 'What boundaries do you need when helping others in recovery?' },
      { id: 's22q15', type: 'exercise', question: 'Write an encouraging message to someone who is just starting their recovery journey.' },
      { id: 's22q16', type: 'journaling', question: 'Describe the feeling of being someone others look up to in recovery.' },
      { id: 's22q17', type: 'reflection', question: 'How can you balance giving to others and taking care of yourself?' },
      { id: 's22q18', type: 'assignment', question: 'Mentor or check in with someone newer in recovery this week. Write about the experience.' },
      { id: 's22q19', type: 'reflection', question: 'What does legacy mean to you in the context of recovery?' },
      { id: 's22q20', type: 'journaling', question: 'Write about the world you want to help create through your recovery and service.' },
    ],
  },
  {
    id: 'sec-23',
    title: 'Long-Term Vision',
    description: 'Plan for a lifetime of recovery and fulfillment',
    unlockMilestoneDays: 365,
    questions: [
      { id: 's23q1', type: 'reflection', question: 'Where do you see yourself in 5 years if you maintain your recovery?' },
      { id: 's23q2', type: 'journaling', question: 'Write a letter from your future self, 10 years sober, to your present self.' },
      { id: 's23q3', type: 'assignment', question: 'Create a comprehensive life plan: 1-year, 3-year, 5-year, and 10-year goals across all life areas.' },
      { id: 's23q4', type: 'reflection', question: 'What does lifelong recovery look like to you? Is there an endpoint?' },
      { id: 's23q5', type: 'journaling', question: 'Describe your ideal life 5 years from now in vivid detail.' },
      { id: 's23q6', type: 'reflection', question: 'What habits and practices will you maintain for the rest of your life?' },
      { id: 's23q7', type: 'assignment', question: 'Create a "recovery maintenance checklist" - daily, weekly, and monthly practices to sustain recovery.' },
      { id: 's23q8', type: 'reflection', question: 'How will you handle life\'s inevitable challenges and maintain sobriety?' },
      { id: 's23q9', type: 'exercise', question: 'Create a vision board (physical or written) for your future. Describe every element.' },
      { id: 's23q10', type: 'reflection', question: 'What is your biggest dream? How does recovery make it possible?' },
      { id: 's23q11', type: 'journaling', question: 'Write your obituary as you would want it to read. What life did you live?' },
      { id: 's23q12', type: 'reflection', question: 'How will you continue to grow and evolve beyond active recovery?' },
      { id: 's23q13', type: 'assignment', question: 'Identify 5 role models who have maintained long-term sobriety. What can you learn from them?' },
      { id: 's23q14', type: 'reflection', question: 'What fears do you have about the future? How can you address them now?' },
      { id: 's23q15', type: 'journaling', question: 'Write about the difference between surviving and thriving. Which one are you doing?' },
      { id: 's23q16', type: 'exercise', question: 'Set one audacious goal that excites and scares you. Write a plan to achieve it.' },
      { id: 's23q17', type: 'reflection', question: 'How will you stay connected to supportive people and routines long-term?' },
      { id: 's23q18', type: 'assignment', question: 'Plan your recovery anniversary celebration. What milestones will you mark and how?' },
      { id: 's23q19', type: 'reflection', question: 'What wisdom do you want to pass on to future generations about addiction and recovery?' },
      { id: 's23q20', type: 'journaling', question: 'Write your recovery manifesto - a declaration of who you are and what you stand for.' },
    ],
  },
  {
    id: 'sec-24',
    title: 'Celebrating Progress',
    description: 'Honor how far you have come',
    unlockMilestoneDays: 730,
    questions: [
      { id: 's24q1', type: 'reflection', question: 'List 20 things that have improved in your life since starting recovery.' },
      { id: 's24q2', type: 'journaling', question: 'Write a detailed comparison of your life before recovery and now.' },
      { id: 's24q3', type: 'assignment', question: 'Create a "victory list" of every accomplishment in your recovery, no matter how small.' },
      { id: 's24q4', type: 'reflection', question: 'How have your relationships changed since beginning recovery?' },
      { id: 's24q5', type: 'exercise', question: 'Call or message 3 people who have supported your recovery. Thank them specifically. Write about the experience.' },
      { id: 's24q6', type: 'journaling', question: 'Write about the hardest day of your recovery and how you overcame it.' },
      { id: 's24q7', type: 'reflection', question: 'What personal qualities have you developed through recovery that you did not have before?' },
      { id: 's24q8', type: 'assignment', question: 'Create a "before and after" comparison across all areas: health, relationships, finances, career, mental health.' },
      { id: 's24q9', type: 'reflection', question: 'What would you tell your day-one self if you could go back in time?' },
      { id: 's24q10', type: 'journaling', question: 'Write a gratitude letter to yourself for every hard decision you made in recovery.' },
      { id: 's24q11', type: 'exercise', question: 'Plan a meaningful celebration for your next recovery milestone. Make it special.' },
      { id: 's24q12', type: 'reflection', question: 'How has your self-perception changed since you started this journey?' },
      { id: 's24q13', type: 'journaling', question: 'Describe the proudest moment of your recovery so far in detail.' },
      { id: 's24q14', type: 'reflection', question: 'What fears from early recovery have you overcome?' },
      { id: 's24q15', type: 'assignment', question: 'Create a "highlight reel" of your recovery journey - the top 10 moments.' },
      { id: 's24q16', type: 'reflection', question: 'How has your physical health improved since getting sober?' },
      { id: 's24q17', type: 'journaling', question: 'Write about the unexpected joys of recovery - things you did not anticipate.' },
      { id: 's24q18', type: 'exercise', question: 'Share your progress with someone you trust. Let them celebrate with you. Write about it.' },
      { id: 's24q19', type: 'reflection', question: 'What does your recovery mean to the people who love you? How has it changed their lives?' },
      { id: 's24q20', type: 'journaling', question: 'Write a love letter to your recovery journey - all the pain, growth, and beauty of it.' },
    ],
  },
  {
    id: 'sec-25',
    title: 'Living Free',
    description: 'Embrace your new life of freedom and fulfillment',
    unlockMilestoneDays: 1095,
    questions: [
      { id: 's25q1', type: 'reflection', question: 'What does freedom mean to you now compared to when you started recovery?' },
      { id: 's25q2', type: 'journaling', question: 'Describe a typical day in your current life. How different is it from your days in active addiction?' },
      { id: 's25q3', type: 'reflection', question: 'What are you most proud of achieving in your recovery?' },
      { id: 's25q4', type: 'assignment', question: 'Write your recovery story from beginning to now. Include the struggles, turning points, and triumphs.' },
      { id: 's25q5', type: 'reflection', question: 'How have your dreams and aspirations evolved throughout recovery?' },
      { id: 's25q6', type: 'exercise', question: 'Spend a day doing everything that represents your best, most authentic self. Write about it.' },
      { id: 's25q7', type: 'journaling', question: 'Write about the person you have become. Would your past self recognize you?' },
      { id: 's25q8', type: 'reflection', question: 'What final pieces of healing still need attention? How will you address them?' },
      { id: 's25q9', type: 'assignment', question: 'Create a "living free" manifesto - your principles for maintaining a fulfilling, sober life.' },
      { id: 's25q10', type: 'reflection', question: 'How can you help ensure that others have the same opportunity for recovery that you had?' },
      { id: 's25q11', type: 'journaling', question: 'Write about the legacy of your recovery. What impact has it had on the world around you?' },
      { id: 's25q12', type: 'exercise', question: 'Do something today you never could have done while in active addiction. Celebrate it fully.' },
      { id: 's25q13', type: 'reflection', question: 'What does living authentically mean to you now?' },
      { id: 's25q14', type: 'assignment', question: 'Write a comprehensive guide to recovery based on everything you have learned. This is your gift to others.' },
      { id: 's25q15', type: 'reflection', question: 'How do you maintain gratitude when life gets routine or challenging?' },
      { id: 's25q16', type: 'journaling', question: 'Write about the interconnection between your recovery, your relationships, your purpose, and your joy.' },
      { id: 's25q17', type: 'reflection', question: 'What is the single most important lesson your recovery has taught you?' },
      { id: 's25q18', type: 'exercise', question: 'Write a letter to someone who is on day one of recovery. Share your hope, your wisdom, and your encouragement.' },
      { id: 's25q19', type: 'reflection', question: 'If you could change anything about your journey, would you? Why or why not?' },
      { id: 's25q20', type: 'journaling', question: 'Write the final chapter of your addiction story and the first chapter of your freedom story. You are the author.' },
    ],
  },
];
